title: "A-SMART Lab"
description: "Applied Systems Modeling, Analytics, Research & Technology"
theme: minima

minima:
  skin: classic

sass:
  sass_dir: assets/css

include:
  - assets/css/style.css

header_pages:
  - PI.md
  - people.md
  - research.md
  - projects.md
  - publications.md
  - collaborators.md
  - sponsors.md
  - news.md
